### ISSUE TITLE
申请 - 姜智豪

### ISSUE THREAD

**Issue by GuessEver** [uestcer/application#100]
- 姓名：姜智豪
- 年级：2014级
- 学院：数学科学学院
- 专业：信息与计算科学，计算机方向
- 方向：Web前端开发、PHP后端开发、iOS开发、win桌面C#开发、Linux开发
- 自我评价：ACM退役，算法基础好，曾组织申报各种创新创业项目，CDOJ iOS开发者，现晴空工作室负责人

**Comment by xudafeng** [comment]
done
