### ISSUE TITLE
请求加入组织

### ISSUE THREAD

**Issue by haiker2011** [uestcer/application#116]
- 姓名：孙海洲
- 年级：已毕业
- 学院：信软学院
- 方向：自然语言处理、云原生
- 自我评价：

**Comment by Xunzhuo** [comment]
LGTM @haiker2011

**Comment by haiker2011** [comment]
不好意思，刚看到链接，好像已经过期了

BIT ***@***.***> 于2021年7月21日周三 下午5:18写道：

**Comment by Xunzhuo** [comment]
@haiker2011 OK 我重新邀请，欢迎～
