### ISSUE TITLE
申请加入组织

### ISSUE THREAD

**Issue by jambestwick** [uestcer/application#129]
- 姓名：jambestwick
- 年级：2008
- 学院：计算机科学与工程学院
- 方向：信息技术与统计学
- 自我评价：founderof china ETC Park APP Leader ,JUST learn

**Comment by jambestwick** [comment]
@Xunzhuo

**Comment by Xunzhuo** [comment]
Hi, I wonder what munchen university means? This is the org for UESTC.

**Comment by jambestwick** [comment]
@Xunzhuo ，格式写错了，sorry

**Comment by Xunzhuo** [comment]
Done and email has been sent. Welcome!

**Comment by jambestwick** [comment]
谢谢
