### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by CNMathon** [uestcer/application#130]
- 姓名：Mathon
- 学院：计算机科学与工程学院
- 方向：计算机科学与技术
- 自我评价：某国家地方联合工程实验室前端负责人

**Comment by Xunzhuo** [comment]
@CNMathon Hi, this is the org for UESTC. From your profile, I can see the different school, maybe should we double check?

**Comment by CNMathon** [comment]
> @CNMathon Hi, this is the org for UESTC. From your profile, I can see the different school, maybe should we double check?

@Xunzhuo The organisation in my profile is the company I currently work for and there is no doubt that my alma mater is UESTC.
